### ISSUE TITLE
ツールのオンオフを1ステップで行いたい

### ISSUE THREAD

**Issue by tokimari** [ymrl/a11y-visualizer#56]
表示したい項目にチェックをつけていると、常に表示されっぱなしになります。
しかしアクセシビリティチェック時以外にも、動作確認や、また、通常の利用をすることもあり、「今のチェックの設定を保持したまま」機能をオン/オフすることができれば、より使いやすくなりそうだなと感じました。

現状では「チップの表示」と「ライブリージョンをアナウンス」のチェックを外すとできそうです。
ただ、再度適用する際に、非エンジニアの場合は、特にライブリージョンの方の適用を忘れてしまうことが考えられます。
また、使用しているつもりもないのに常に動き続けている…というのも些か気持ち悪いです（すみません）

[v1.0.1で追加された、ホストごとの設定保存](https://github.com/ymrl/a11y-visualizer/releases/tag/v1.0.1)の結果、ホストごとに逐一オフにしていく必要があり、煩わしくなり大元の拡張機能設定でOFFにされてしまうことも懸念しています。

（既にそのような機能が提供されていれば申し訳ありません・・・！）

Accessibility Visualizer、とても便利で感動しました！😄 
HTMLの知識のない非エンジニアのアクセシビリティチェックにも導入して活用していきたいなと思っております！特に入稿やスタッフブログなどのチェックに最適ではと考えています。
お忙しいとは思いますが、ご検討よろしくお願いします。

**Comment by ymrl** [comment]
活用ありがとうございます！

いちおう、拡張機能のオプション（Accessibility Visualizerのアイコンを右クリック→オプション or Chromeの設定画面→拡張機能→Accessibility Visualizer→拡張機能のオプション）で、初めて訪問するホストでのデフォルト設定が設定できるようになっています

<img width="372" alt="Accessibility Visualizerのアイコンを右クリック→メニューからオプションを選んでいるところ" src="https://github.com/ymrl/a11y-visualizer/assets/154188/186096ed-96f3-4aef-8734-8114efca1006">
<img width="475" alt="Accessibility Visualizerのオプション画面" src="https://github.com/ymrl/a11y-visualizer/assets/154188/0e49d33e-dd77-477c-8a5c-c4650ddd0450">

なんですが、

> ただ、再度適用する際に、非エンジニアの場合は、特にライブリージョンの方の適用を忘れてしまうことが考えられます。
> また、使用しているつもりもないのに常に動き続けている…というのも些か気持ち悪いです（すみません）

これについては、「たしかに……！！」というところなので、全部の設定を一括ON/OFFするような操作は考えてみてよさそうに思いました。前向きに検討します。

**Comment by tokimari** [comment]
早速ご確認＆ご検討いただけるとのことで、ありがとうございます 😍 

> 拡張機能のオプション（Accessibility Visualizerのアイコンを右クリック→オプション or Chromeの設定画面→拡張機能→Accessibility Visualizer→拡張機能のオプション）で、初めて訪問するホストでのデフォルト設定が設定できるようになっています。なのでとりあえずここでオフにしておけば、いろんなサイトにいくたびオフにする操作は要らなくなります。

なるほど・・！
「オプションからの設定」と、通常の「拡張機能のポップアップからの設定」での振る舞いの違いを理解できていなかったです。たしかに下記のように書かれていました。ありがとうございます！ 🙏 

> 拡張機能のポップアップから設定を変更すると、閲覧中のWebページのホストごとに設定が保存され、同じホストのWebページに対して適用されます。この画面で設定を変更しても、それらの設定値は変更されません。

私のようによくアクセシビリティをチェックしたい人にとってはそれで良さそうなので、もう少し使ってみて社内でどう利用しようか検討したいと思います 😄
