### ISSUE TITLE
Translate Users' Guide to English

### ISSUE THREAD

**Issue by ymrl** [ymrl/a11y-visualizer#6]
I think it is important to provide English information of this extension, but because this is my personal project, there isn't much time for me to create documents in multi languages.

I wrote Users' Guide in Japanese for users who installed this extension at first time. 

https://github.com/ymrl/a11y-visualizer/blob/main/docs/ja/UsersGuide.md

This is most important document because they cannot understand what it provides and what they have to do without it.

If you can help us, please Pull Request to create `docs/en/UsersGuide.md` .

**Comment by harshilshah99** [comment]
@ymrl I have translated user guide to english can you review it

**Comment by ymrl** [comment]
Thank you @harshilshah99 , I will review it.
