### ISSUE TITLE
「有効」のチェックを外していても、拡張機能が`</body>`の直前に`<div>`を生成する

### ISSUE THREAD

**Issue by miralkashiwagi** [ymrl/a11y-visualizer#93]
拡張機能ありがとうございます！
とても助けられておりますが、
以下に記載の状況により、拡張機能をインストールしたり削除したりを繰り返さざるを得ないため報告いたします！

## 環境
Windows 10
Chrome 125
Accessibility Visualizer 3.1.0

## 状況
Accessibility Visualizer の設定で「有効」のチェックを外していても、拡張機能が`</body>`の直前に`<div>`を生成する
▼ https://example.com/ を閲覧した場合の表示
![image](https://github.com/ymrl/a11y-visualizer/assets/36557632/2826388a-95b5-4d44-a192-af72195a04ed)

## 上記に伴い発生している問題
Accessibility Visualizer の設定で「有効」のチェックを外していても
WordPressのクラシックエディター（またはWordPressのAdvanced Custom Filedで生成したウィジウィグ入力欄 ：つまりTinyMCE？）にてビジュアルモードで編集を行うと、登録データに`<div>`が追加されてしまう。
（ページを保存後、編集画面を再読み込み＆保存すると、さらに `<div>` が追加されます）

※ できれば不要な `<div>` は登録したくないため、現在は、通常時は拡張機能を削除しておくことで問題を解決しています。

▼ WordPressのクラシックエディターを操作しているところ
![image](https://github.com/ymrl/a11y-visualizer/assets/36557632/a8ff8e93-40ee-4c64-a849-820ceb543415)

▼ WordPressのクラシックエディターを「テキスト」に切り替え実際のデータを確認しているところ
![image](https://github.com/ymrl/a11y-visualizer/assets/36557632/295f8cbe-c16b-4397-a6ea-8da463f6525e)

## 確認したこと
Accessibility Visualizer拡張機能を削除すれば、上記の状況は発生しません

## こうなると嬉しいです
Accessibility Visualizer の設定で「有効」のチェックを外している場合は`<div>`を生成しない

---

拡張機能の仕組み上難しいなどあるかもしれませんので、可能であればご検討いただけますと幸いです！

**Comment by ymrl** [comment]
なるほど、WYSIWIGエディタに影響が出てしまうのはマズいですね。対策を考えてみます！

**Comment by ymrl** [comment]
3.2.2にて修正されているはずです

**Comment by miralkashiwagi** [comment]
@ymrl ありがとうございます！
修正されたことを確認いたしました。感謝いたします…！
